export type Security = {
  instrument_type: string | null;
  coupon: unknown | null;
  issue_price: unknown | null;
  display: string | null;
  asset_subclass: string | null;
  market_value: number | null;
  rate: unknown | null;
  book: unknown | null;
  symbol: string | null;
  percent_index: unknown | null;
  settlement: unknown | null;
  issuer_type: unknown | null;
  label: string | null;
  accounting: unknown | null;
  market_price: number | null;
  hash: string | null;
  extra_data: unknown | null;
  multiplier: number | null;
  option_type: unknown | null;
  error_type: string | null;
  exchange: string | null;
  premium: unknown | null;
  fx_rate: number | null;
  ticker: string | null;
  status: string | null;
  currency: string | null;
  operation: unknown | null;
  comparable: string | null;
  market_value_in_base: number | null;
  issuer: unknown | null;
  unrealized_pl_in_base: number | null;
  unrealized_pl: number | null;
  instrument_class: string | null;
  issue_date: unknown | null;
  series: unknown | null;
  quantity: number | null;
  id: string | null;
  cost_price: number | null;
  isin: string | null;
  strike: unknown | null;
  asset_class: string | null;
  look_through_reference: unknown | null;
  return_date: unknown | null;
  underlying: unknown | null;
  maturity_date: unknown | null;
  previous_quantity: number | null;
  warranty: unknown | null;
  name: string | null;
  error_message: string | null;
  indexer: unknown | null;
  trader: unknown | null;
  trade_id: unknown | null;
};

export type Portfolio = {
    id:string;
    name?:string;
    description?:string;
    base_currency:string;
    securities:Security[];
    nlv?:number;
    date:string;
    date_time?:string;
    tags?:string[];
    workspace:string;
    created?:number;
    updated?:number;
    version?:string;
    link_uid?:string|null;
    level?:string|null;
    storage?:boolean;
    check_securities?:boolean;
}
